import pptxgen from "pptxgenjs";

export const createPresentationBuffer = async (presentation: {
  metadata: {
    title: string;
    subject?: string;
  };
  slides: {
    slideNumber: number;
    title: string;
    bulletPoints: string[];
    teacherNotes?: string;
  }[];
}): Promise<Buffer> => {
  const pres = new pptxgen();
  
  // Set layout widescreen 16:9
  pres.layout = "LAYOUT_16x9";

  // 1. Create Title Slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { fill: "1e293b" }; // Dark Slate background
  
  // Title text
  titleSlide.addText(presentation.metadata.title, {
    x: 1.0,
    y: 2.0,
    w: 8.0,
    h: 1.5,
    fontSize: 40,
    bold: true,
    color: "ffffff",
    fontFace: "Arial",
  });

  // Subtitle
  titleSlide.addText(`Subject: ${presentation.metadata.subject || "General Course"}\nGenerated by VedaAI`, {
    x: 1.0,
    y: 3.8,
    w: 8.0,
    h: 1.0,
    fontSize: 18,
    color: "ea580c", // Brand Orange accent
    fontFace: "Arial",
  });

  // 2. Content Slides
  presentation.slides.forEach((slide) => {
    const s = pres.addSlide();
    s.background = { fill: "f8fafc" }; // Soft off-white

    // Slide Header Top Bar Accent
    s.addShape(pres.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 10,
      h: 0.15,
      fill: { color: "ea580c" },
    });

    // Slide Title
    s.addText(slide.title, {
      x: 0.8,
      y: 0.5,
      w: 8.4,
      h: 0.8,
      fontSize: 28,
      bold: true,
      color: "0f172a",
      fontFace: "Arial",
    });

    // Bullet Points
    const bulletText = slide.bulletPoints.map((bp) => ({
      text: bp,
      options: { bullet: true, fontSize: 16, color: "334155", fontFace: "Arial" }
    }));
    
    // Add text with bullets
    s.addText(bulletText, {
      x: 0.8,
      y: 1.6,
      w: 8.4,
      h: 4.0,
      valign: "top",
    });

    // Slide Number Footer
    s.addText(`Slide ${slide.slideNumber}`, {
      x: 8.5,
      y: 6.8,
      w: 1.0,
      h: 0.3,
      fontSize: 10,
      color: "94a3b8",
      align: "right",
    });

    // Embed Speaker Notes
    if (slide.teacherNotes) {
      s.addNotes(slide.teacherNotes);
    }
  });

  const buffer = await pres.write({ outputType: "nodebuffer" });
  return buffer as Buffer;
};
