import { useState, useEffect } from "react";
import { useParams, useNavigate, useLocation } from "react-router-dom";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { TopicHeader } from "@/components/topic/TopicHeader";
import { LearningObjectivesCard } from "@/components/topic/LearningObjectivesCard";
import { DetailedExplanationCard } from "@/components/topic/DetailedExplanationCard";
import { KeyConceptsCard } from "@/components/topic/KeyConceptsCard";
import { PracticalExamplesCard } from "@/components/topic/PracticalExamplesCard";
import { YouTubeVideosCard } from "@/components/topic/YouTubeVideosCard";
import { pdfApi } from "@/lib/api";
import { toast } from "@/hooks/use-toast";

interface TopicDetail {
  title: string;
  unit: number;
  learningObjectives: string[];
  detailedExplanation: string;
  keyConcepts: string[];
  practicalExamples: string[];
  youtubeVideos: {
    videoId: string;
    title: string;
    thumbnail: string;
    channelName: string;
    duration: string;
    viewCount: string;
  }[];
}

const TopicDetail = () => {
  const { pdfId, unitIndex, topicIndex } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const [topicDetail, setTopicDetail] = useState<TopicDetail | null>(null);
  const [loading, setLoading] = useState(true);

  const { topicTitle, topicSummary } = location.state || {};

  useEffect(() => {
    const fetchExplanation = async () => {
      let title = topicTitle;
      let summary = topicSummary;

      // If state is missing (e.g. refresh), fetch from roadmap
      if (!title && pdfId) {
        try {
          const res = await pdfApi.getRoadmapForPDF(pdfId);
          const roadmap = res.data.roadmap;
          const unit = roadmap[unitIndex || "0"];
          const topic = unit?.topics?.[topicIndex || "0"];

          if (topic) {
            title = topic.title;
            summary = topic.summary;
          }
        } catch (e) {
          console.error("Failed to fetch roadmap for context", e);
        }
      }

      if (!pdfId || !title) {
        setLoading(false);
        return;
      }

      try {
        const response = await pdfApi.explainTopic(
          pdfId,
          parseInt(unitIndex || "0"),
          parseInt(topicIndex || "0"),
          { topicTitle: title, topicSummary: summary }
        );

        const data = response.data;

        setTopicDetail({
          title: title,
          unit: parseInt(unitIndex || "0"),
          learningObjectives: data.explanation.learningObjectives,
          detailedExplanation: data.explanation.detailedExplanation,
          keyConcepts: data.explanation.keyConcepts,
          practicalExamples: data.explanation.practicalExamples,
          youtubeVideos: data.youtubeVideos
        });

        if (data.cached) {
          toast({ title: "Loaded from cache", description: "Topic explanation loaded instantly." });
        } else {
          toast({ title: "Generated successfully", description: "Topic explanation generated by AI." });
        }

      } catch (error) {
        console.error(error);
        toast({
          title: "Error",
          description: "Failed to generate topic explanation",
          variant: "destructive",
        });
      } finally {
        setLoading(false);
      }
    };

    fetchExplanation();
  }, [pdfId, unitIndex, topicIndex, topicTitle, topicSummary]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent"></div>
      </div>
    );
  }

  if (!topicDetail) {
    return (
      <div className="flex min-h-screen flex-col">
        <Navbar />
        <main className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <h2 className="text-2xl font-bold mb-2">Topic Not Found</h2>
            <p className="text-muted-foreground mb-4">Could not load topic details.</p>
            <button onClick={() => navigate(-1)} className="text-primary hover:underline">
              Go Back
            </button>
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-gray-50">
      <Navbar />
      <main className="container mx-auto px-4 py-8">
        <TopicHeader
          topic={topicDetail}
          unitIndex={parseInt(unitIndex || "0")}
          onBack={() => navigate(-1)}
        />

        <div className="mt-8 grid grid-cols-1 lg:grid-cols-5 gap-8">
          <div className="lg:col-span-3 space-y-6">
            <LearningObjectivesCard objectives={topicDetail.learningObjectives} />
            <DetailedExplanationCard explanation={topicDetail.detailedExplanation} />
            <KeyConceptsCard concepts={topicDetail.keyConcepts} />
            <PracticalExamplesCard examples={topicDetail.practicalExamples} />
          </div>

          <div className="lg:col-span-2">
            <YouTubeVideosCard videos={topicDetail.youtubeVideos} />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TopicDetail;
